# Generated by Django 4.2.1 on 2023-05-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogo', models.CharField(max_length=150)),
                ('plataforma', models.CharField(max_length=100)),
                ('desenvolvedor', models.CharField(max_length=150)),
            ],
        ),
    ]
